
language: d

d:
    - dmd-2.077.1
    - ldc-1.7.0
os:
    - linux

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev

script:
- dub build --override-config vibe-d:tls/openssl
- dub test --override-config vibe-d:tls/openssl
